const fs = require('fs');
let c = fs.readFileSync('public/presupuesto.html', 'utf8');
const lines = c.split('\n');
lines[665] = "      let msg = 'Hola ' + cliente + '! Te enviamos el presupuesto ' + num + ' de Neumaticos Gallo.\\n\\n';";
lines[666] = '';
lines[667] = '';
lines[668] = '';
lines[677] = "        msg += p.descripcion + ' x' + cant + '\\n';";
lines[678] = '';
lines[679] = "        if (fp12) msg += '  12 pagos: ' + fmt(c12) + '\\n';";
lines[680] = "        if (fp6)  msg += '  6 cuotas (-10%): ' + fmt(c6t) + ' (' + fmt(c6c) + '/cuota)\\n';";
lines[681] = "        if (fp3)  msg += '  3 cuotas (-15%): ' + fmt(c3t) + ' (' + fmt(c3c) + '/cuota)\\n';";
lines[682] = "        if (fp1)  msg += '  Contado (-20%): ' + fmt(c1) + '\\n';";
lines[690] = "        msg += 'Servicios: ' + sPartes.join(', ') + ' aprox. ' + fmt(ssPrecio) + ' (' + ssPago + ')\\n\\n';";
lines[692] = "      if (linkPublico) { msg += 'Ver presupuesto completo: ' + linkPublico + '\\n\\n'; }";
lines[693] = "      msg += 'Garantia 5 anos. Colocacion sin cargo.\\n';";
lines[694] = "      msg += 'Victoria: 11-3773-5246 | Nordelta: 11-5734-7692\\n';";
lines[695] = "      msg += 'tienda.neumaticosgallo.com.ar';";
lines[696] = '';
fs.writeFileSync('public/presupuesto.html', lines.join('\n'), 'utf8');
console.log('OK');
